/**
 * Sprint 75 — GitHub Push Logic
 * Extracted from pipeline-publish/index.ts.
 * Handles: repo creation/check, blob creation, tree building, atomic commit.
 */

import type { FileEntry } from "./publish-helpers.ts";
import { sanitizeTreePath } from "./publish-helpers.ts";

const GITHUB_API = "https://api.github.com";

export interface GitHubPushResult {
  commitSha: string;
  committedFiles: string[];
  skippedFiles: string[];
  repoHtmlUrl: string;
  actualOwner: string;
  actualRepo: string;
}

export interface GitHubPushOptions {
  ghHeaders: Record<string, string>;
  owner: string;
  repo: string;
  baseBranch: string;
  initiativeTitle: string;
  fileEntries: FileEntry[];
  commitMessages: string[];
  version: string;
}

/**
 * Ensure the target repo exists, creating it if necessary.
 * Returns the confirmed owner, repo name, and HTML URL.
 */
export async function ensureRepoExists(
  ghHeaders: Record<string, string>,
  owner: string,
  repo: string,
  description: string,
): Promise<{ actualOwner: string; actualRepo: string; repoHtmlUrl: string }> {
  let actualOwner = owner;
  let actualRepo = repo;
  let repoHtmlUrl = `https://github.com/${owner}/${repo}`;

  const repoCheckResp = await fetch(`${GITHUB_API}/repos/${owner}/${repo}`, { headers: ghHeaders });
  if (!repoCheckResp.ok) {
    let createUrl = `${GITHUB_API}/user/repos`;
    const createBody: any = { name: repo, description, private: false, auto_init: true };
    const orgCheck = await fetch(`${GITHUB_API}/orgs/${owner}`, { headers: ghHeaders });
    if (orgCheck.ok) createUrl = `${GITHUB_API}/orgs/${owner}/repos`;

    const createRepoResp = await fetch(createUrl, {
      method: "POST", headers: ghHeaders, body: JSON.stringify(createBody),
    });
    if (createRepoResp.ok) {
      const repoData = await createRepoResp.json();
      actualOwner = repoData.owner?.login || owner;
      actualRepo = repoData.name || repo;
      repoHtmlUrl = repoData.html_url;
    } else {
      const errData = await createRepoResp.json();
      if (!errData.errors?.[0]?.message?.includes("name already exists")) {
        throw new Error(`Falha ao criar repositório: ${errData.message}`);
      }
    }
    await new Promise(r => setTimeout(r, 2000));
  } else {
    const repoData = await repoCheckResp.json();
    repoHtmlUrl = repoData.html_url || repoHtmlUrl;
  }

  return { actualOwner, actualRepo, repoHtmlUrl };
}

/**
 * Get the SHA of the base branch, seeding if necessary.
 */
export async function getBaseBranchSha(
  ghHeaders: Record<string, string>,
  owner: string,
  repo: string,
  baseBranch: string,
  initiativeTitle: string,
): Promise<string> {
  const refResp = await fetch(
    `${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`,
    { headers: ghHeaders },
  );
  if (!refResp.ok) {
    // Seed the branch with a README
    await fetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/README.md`, {
      method: "PUT",
      headers: ghHeaders,
      body: JSON.stringify({
        message: "Initial commit",
        content: btoa(`# ${initiativeTitle}\n\nGenerated by AxionOS`),
      }),
    });
    await new Promise(r => setTimeout(r, 1500));
  }

  const refResp2 = await fetch(
    `${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`,
    { headers: ghHeaders },
  );
  if (!refResp2.ok) throw new Error(`Branch '${baseBranch}' não encontrada após seed.`);
  const refData = await refResp2.json();
  return refData.object.sha;
}

/**
 * Perform the atomic GitHub push: blobs → tree → commit → update ref.
 * Sanitizes all file paths to prevent trailing-slash 422 errors.
 */
export async function atomicGitHubPush(opts: GitHubPushOptions): Promise<GitHubPushResult> {
  const { ghHeaders, owner, repo, baseBranch, initiativeTitle, fileEntries, commitMessages, version } = opts;

  const { actualOwner, actualRepo, repoHtmlUrl } = await ensureRepoExists(
    ghHeaders, owner, repo,
    `${initiativeTitle} — Gerado pelo AxionOS`,
  );

  const baseSha = await getBaseBranchSha(ghHeaders, actualOwner, actualRepo, baseBranch, initiativeTitle);

  // ── Step 1: Create blobs (parallel batches of 5) ──
  const BLOB_BATCH = 5;
  const treeItems: Array<{ path: string; mode: string; type: string; sha: string }> = [];
  const committedFiles: string[] = [];
  const skippedFiles: string[] = [];

  for (let i = 0; i < fileEntries.length; i += BLOB_BATCH) {
    const batch = fileEntries.slice(i, i + BLOB_BATCH);
    const blobResults = await Promise.allSettled(
      batch.map(async (file) => {
        const blobResp = await fetch(
          `${GITHUB_API}/repos/${actualOwner}/${actualRepo}/git/blobs`,
          {
            method: "POST",
            headers: ghHeaders,
            body: JSON.stringify({ content: file.content, encoding: "utf-8" }),
          },
        );
        if (!blobResp.ok) {
          const errText = await blobResp.text();
          throw new Error(`Blob creation failed for ${file.path}: ${errText}`);
        }
        const blobData = await blobResp.json();
        return { path: file.path, sha: blobData.sha };
      }),
    );

    for (let j = 0; j < blobResults.length; j++) {
      const result = blobResults[j];
      const file = batch[j];
      if (result.status === "fulfilled") {
        // ★ CRITICAL FIX: sanitize path to prevent trailing-slash 422
        const cleanPath = sanitizeTreePath(result.value.path);
        if (!cleanPath) {
          skippedFiles.push(file.path);
          continue;
        }
        treeItems.push({ path: cleanPath, mode: "100644", type: "blob", sha: result.value.sha });
        committedFiles.push(cleanPath);
      } else {
        console.error(`Blob failed for ${file.path}:`, result.reason);
        skippedFiles.push(file.path);
      }
    }
  }

  if (treeItems.length === 0) throw new Error("Nenhum blob criado — falha total");

  // ── Step 2: Create tree ──
  const treeResp = await fetch(
    `${GITHUB_API}/repos/${actualOwner}/${actualRepo}/git/trees`,
    {
      method: "POST",
      headers: ghHeaders,
      body: JSON.stringify({ tree: treeItems }),
    },
  );
  if (!treeResp.ok) {
    const errText = await treeResp.text();
    throw new Error(`Tree creation failed: ${errText}`);
  }
  const newTree = await treeResp.json();

  // ── Step 3: Create atomic commit ──
  const commitMessage = `feat: ${initiativeTitle} v${version}\n\n${
    committedFiles.length} files generated by AxionOS Release Agent\n\n${
    commitMessages.slice(0, 10).map((m: string) => `- ${m}`).join("\n")}`;

  const commitResp = await fetch(
    `${GITHUB_API}/repos/${actualOwner}/${actualRepo}/git/commits`,
    {
      method: "POST",
      headers: ghHeaders,
      body: JSON.stringify({ message: commitMessage, tree: newTree.sha, parents: [baseSha] }),
    },
  );
  if (!commitResp.ok) {
    const errText = await commitResp.text();
    throw new Error(`Commit creation failed: ${errText}`);
  }
  const newCommit = await commitResp.json();

  // ── Step 4: Update branch ref ──
  const updateRefResp = await fetch(
    `${GITHUB_API}/repos/${actualOwner}/${actualRepo}/git/refs/heads/${baseBranch}`,
    {
      method: "PATCH",
      headers: ghHeaders,
      body: JSON.stringify({ sha: newCommit.sha, force: true }),
    },
  );
  if (!updateRefResp.ok) {
    const errText = await updateRefResp.text();
    throw new Error(`Ref update failed: ${errText}`);
  }

  return {
    commitSha: newCommit.sha,
    committedFiles,
    skippedFiles,
    repoHtmlUrl,
    actualOwner,
    actualRepo,
  };
}
