
ALTER TABLE public.initiatives
  ADD COLUMN IF NOT EXISTS deploy_error_code TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS deploy_error_message TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_deploy_check_at TIMESTAMP WITH TIME ZONE DEFAULT NULL;
