-- Add new agent roles for the 6-layer architecture
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'vision_agent';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'market_analyst';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'requirements_agent';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'product_architect';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'system_architect';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'data_architect';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'api_architect';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'dependency_planner';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'task_planner';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'story_generator';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'file_planner';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'code_architect';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'developer';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'integration_agent';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'static_analysis';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'runtime_qa';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'fix_agent';
ALTER TYPE public.agent_role ADD VALUE IF NOT EXISTS 'release_agent';